---
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart forgejo_db
  ansible.builtin.systemd:
    name: forgejo_db
    state: restarted
    daemon_reload: true

- name: Restart forgejo
  ansible.builtin.systemd:
    name: forgejo
    state: restarted
    daemon_reload: true
