---
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart nextcloud_db
  ansible.builtin.systemd:
    name: nextcloud_db
    state: restarted
    daemon_reload: true

- name: Restart nextcloud_redis
  ansible.builtin.systemd:
    name: nextcloud_redis
    state: restarted
    daemon_reload: true

- name: Restart nextcloud
  ansible.builtin.systemd:
    name: nextcloud
    state: restarted
    daemon_reload: true
